
public class ObjectsCreate {

	String name="SachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachininSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachinSachin";
	int age=30;
	String city="Dehradun";
	long phoneNumber=9999999999l;
	public static void main(String[] args) {
		
		for (int i = 0; ; i++) {
			ObjectsCreate obj=new ObjectsCreate();
			System.out.println(i+"-->"+obj);
		}
			
		}
	}


